version: '3.9'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  frontend:
    container_name: client
    build: ./client
    ports:
      - "80:80"
  backend:
    container_name: server
    build: ./server
    ports:
      - "3001:3001"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"